### ISSUE TITLE
Is there any piece of code that will save the results?

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [EdwardSmith1884/GEOMetrics#10]
By using your pre-trained weights, we could get the reconstructed mesh.
And by setting "eval_vis" in GEOMetrics.py to be true, we could visualize the results. 
is there any way to save visualization of the generated mesh?

**Comment by EdwardSmith1884** [comment]
use the function [here](https://github.com/EdwardSmith1884/GEOMetrics/blob/09471d70f441482319543bb5214eaaab38f64507/voxel.py#L98)

**Comment by Zhangsihao-Yang** [comment]
Sorry for not clarifying it. 
I mean do you provide any visualization code that could save the image of the rendered mesh.

**Comment by EdwardSmith1884** [comment]
ah, no sorry I do not

**Comment by Zhangsihao-Yang** [comment]
> use the function [here](https://github.com/EdwardSmith1884/GEOMetrics/blob/09471d70f441482319543bb5214eaaab38f64507/voxel.py#L98)

**Comment by Zhangsihao-Yang** [comment]
Thanks!
