### ISSUE TITLE
Where is the code of adaptive face splitting?

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [EdwardSmith1884/GEOMetrics#11]
I did not see the code that does the adaptive face splitting in GEOMetric.py.
Could you guide me to the position?

**Comment by Zhangsihao-Yang** [comment]
I could see that part of the code in the old_GEOMetrics folder. But should it be used in the new folder?

**Comment by EdwardSmith1884** [comment]
No, I leave it out in the interest of large speed ups from vectorization.

**Comment by KnightOfTheMoonlight** [comment]
Could you make it public? @EdwardSmith1884. It looks like you treat the face split part as an end-to-end learning part for your whole project. However, after the face split, the adjacency matrix should be updated. If it is a post-process part, then It has no effect at all, cause this part will have not affect to the mesh deformation part.

**Comment by EdwardSmith1884** [comment]
@KnightOfTheMoonlight the code is public already [here](https://github.com/EdwardSmith1884/GEOMetrics/tree/master/old_GEOMetrics).  Face splitting is not a post-processing step. It happens during learning. Quite a bit of work was put into making the adjacency matrix update somewhat efficient.

**Comment by KnightOfTheMoonlight** [comment]
@EdwardSmith1884 as your updated code does not contain the face slit part, your updated results from this comment https://github.com/EdwardSmith1884/GEOMetrics/issues/1#issuecomment-593428137 are obtained from no face split part too?

**Comment by EdwardSmith1884** [comment]
Yes this is with no space splitting.

**Comment by KnightOfTheMoonlight** [comment]
@EdwardSmith1884 Then this is against your ablation study part in your paper. Table 2. You have proven face split has improved the performance from `50.33` to `56.61` for the `chair` category.

**Comment by EdwardSmith1884** [comment]
No, this improvement is from: 
- using different regularization parameters 
- training with all classes simultaneously 
- the increased training time afforded by increased speed of the model. 

The face splitting was removed so that I could vectorize the training process, and make it as fast as possible.
