### ISSUE TITLE
Where to download ShapeNet Images

### ISSUE THREAD

**Issue by otmanon** [EdwardSmith1884/GEOMetrics#14]
Hello! This is a question I have for using this with kaolin as well... you guys refer to using mesh models from shapenetCore, which I have, but then you also refer to a shapenet images dataset... can you clarify what that is, and where I can get it? Should I already have it with ShapeNet core? Because all I have are .obj files + materials.

**Comment by EdwardSmith1884** [comment]
ShapeNet is a dataset of meshes. These meshes have been rendered into images. I supply a script to download these images [here](https://github.com/EdwardSmith1884/GEOMetrics/blob/09471d70f441482319543bb5214eaaab38f64507/data_prep.py#L389).
