### ISSUE TITLE
Dockerfile available?

### ISSUE THREAD

**Issue by KunalMGupta** [EdwardSmith1884/GEOMetrics#15]
I wish to run your code inside kubernete containers. Is there a dockerfile available to run GEOMetrics?

Thanks

**Comment by EdwardSmith1884** [comment]
Sorry there is no dockerfile available. I am not familiar with kubernete containers, is there something preventing you from using the code directly within them?

**Comment by KunalMGupta** [comment]
Hi. Actually the data preparation scripts require blender which I am not able to run inside a container. Is there some other way to do data preparation which can work inside containers? Or is it possible to access the preprocessed data?

Thanks.

**Comment by EdwardSmith1884** [comment]
Ah I see the problem. I would just say avoid the blender processing [here](https://github.com/EdwardSmith1884/GEOMetrics/blob/09471d70f441482319543bb5214eaaab38f64507/data_prep.py#L105), as it is only required for using the latent loss, which is turned off by default anyway.
