### ISSUE TITLE
Camera matrix requirement

### ISSUE THREAD

**Issue by otmanon** [EdwardSmith1884/GEOMetrics#16]
Hi Edward, I notice that to evaluate this model we need an image as well as some camera properties, like the camera position/viewing direction etc. How important would you say this is? For my current project I do not have access to this information... Can you think of a quick way to "hack" this part? Let me know,
Thanks
Otman

**Comment by EdwardSmith1884** [comment]
Hi Otman,
It kinda depends on where you got the images from, are they real images, are they from ShapeNet? Can you let me know where you got them from. I can pretty much guarantee the method will fail without them, though they can be predicted if you are willing to retrain a model from scratch.

**Comment by otmanon** [comment]
Hi Edward!
They are real images unfortunately! I'm all ears on how to predict them though!

**Comment by EdwardSmith1884** [comment]
Ah, with real images the problem becomes a lot harder unfortunately. It would be a project within itself. That's not to say that it is impossible but it would require a lot of planning.  I would suggest emailing me directly if you wish to discuss how to make this possible.
