### ISSUE TITLE
Vertices from shapenet models

### ISSUE THREAD

**Issue by BornInWater** [EdwardSmith1884/GEOMetrics#2]
ShapeNet models have large number of vertices[eg: 26000 vertices for car models] but your model generates much lesser vertices. So, are the ground truth meshes converted to low resolution before finding the chamfer distance?
Also, some of those vertices in the ground truth correspond to the interior of the car like below
![car_interior](https://user-images.githubusercontent.com/36148827/57087217-937c4080-6ccd-11e9-9f17-61ce26d4e715.png)

Do you just ignore those vertices or just let them be there for the chamfer distance calculation?

**Comment by EdwardSmith1884** [comment]
So the vertex simplification is only for computing the latent loss. When training and evaluating using the chamfer loss we do not use simplified meshes, however we do only use the surface information and internal mesh information is removed
