### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by shersoni610** [EdwardSmith1884/GEOMetrics#4]
Hello Edwards,

I am trying to understand your code. I am a newbie to python and Machine learning.
I have a naive question. After training the data, how do I supply input dataset (i.e. image)
to get a triangulated model?

**Comment by EdwardSmith1884** [comment]
urr you could put it in a folder mimicking the data layout I already have. You would have to know the camera parameters of the image however.

**Comment by KnightOfTheMoonlight** [comment]
Is the final result based on epoch 3000? From your code https://github.com/EdwardSmith1884/GEOMetrics/blob/09471d70f441482319543bb5214eaaab38f64507/GEOMetrics.py#L375, I found there are 3000 epochs. And I didn't find the experiment details in your ICML2019 paper.

**Comment by EdwardSmith1884** [comment]
no, I check the validation error regularly and stop training when the f1 score stops increasing.
