### ISSUE TITLE
Could you share the generated data with me?

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [EdwardSmith1884/GEOMetrics#6]
I tried to run 
`python data_prep.py.`
But it seems that it did not generate the correct dataset. Maybe because some of the files is missing.

**Comment by EdwardSmith1884** [comment]
hi can you try setting the debug flag to true [here](https://github.com/EdwardSmith1884/GEOMetrics/blob/09471d70f441482319543bb5214eaaab38f64507/data_prep.py#L44)  and seeing what error messages you get when you run it again? Just post the error you get and I can try to help. For debugging purposes I would also suggested setting the number of objects to 3.

**Comment by Zhangsihao-Yang** [comment]
The error looks like the following image.
![image](https://user-images.githubusercontent.com/29811853/73411642-f4679200-42ba-11ea-867c-94b78c86b4c9.png)

**Comment by EdwardSmith1884** [comment]
ah so you just need to install that library: lib3ds-1.so.3 

probably: sudo apt-get install lib3ds-1-3

**Comment by Zhangsihao-Yang** [comment]
By the way, do you think the number "4692/4692" shown in the above picture is correct?
Because for downscaling that number is around 6500.

**Comment by EdwardSmith1884** [comment]
yes, as that is just the training set I think

**Comment by Zhangsihao-Yang** [comment]
Thanks a lot!
