### ISSUE TITLE
Do I must have sudo permission to run binvox?

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [EdwardSmith1884/GEOMetrics#7]
I tried to run
`sudo chmod 777 scripts/binvox`
without `sudo`.

But when I run
`python data_prep.py`
it shows the following mistake:

> AssertionError: The binvox executable failed. Please check its permissions

**Comment by EdwardSmith1884** [comment]
can you check the permissions of the file to see if you can run it:

ls -l scripts/binvox

**Comment by Zhangsihao-Yang** [comment]
And the above command line gives me the following output:

> -rwxrwxrwx 1 <my_name> <machine_name> 348956 Jan 29 14:17 scripts/binvox

do you know what is the meaning of it?

**Comment by EdwardSmith1884** [comment]
hmm, looks like you do have permissions to run it, can you try running it outside of the script? just call it directly and show me the output?

**Comment by Zhangsihao-Yang** [comment]
The problem is solved. see issue @ #6
